// Ultraman Fighting Evolution 3 (SLPS-25441) runtime overrides.
#include "game_overrides.h"
#include "ps2_runtime.h"
#include "runtime/ps2_memory.h"
#include "runtime/ee_scheduler.h"

#include "erx_tables.h"

#include <cstdint>
#include <cstdarg>
#include <cctype>
#include <cstdio>
#include <cstdlib>
#include <algorithm>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <string>
#include <vector>

// Generated by erx/step2/erx_post.py into src/runner/erx/erx_register.cpp:
// registers every recompiled ERX module function in PS2Runtime's overflow
// registry. Called at runtime-init time (NOT via a static initializer -- see the
// comment in erx_post.py about static initialization order).
void erxRegisterModuleFunctions();

namespace
{
    void applyUfe3(PS2Runtime &runtime);

    // ---------------------------------------------------------------------------
    // SOUNDMAN load bypass.
    //
    // The game's stream/load queue (sub_0032F050, entries at 0x4C0550) sends bulk
    // FILE1-4.BIN reads to the game's SOUNDMAN.IRX over SIF RPC:
    //   sub_00356948 = cmd 0x1A, sub_00356998 = cmd 0x1B ("load file range"),
    //   sub_00356A18 = cmd 0x1D ("is job done?").
    // The EE-side pipeline is correct, but the runtime's IOP emulation cannot run
    // SOUNDMAN's job engine to completion (the per-slot worker threads deadlock on
    // the module's shared semaphore, job state 7's WaitSema).  That is a runtime gap,
    // so we replace just these three RPC entry points with a synchronous
    // implementation of the same request.  All queue walking, phasing, and the LZSS
    // post-load step (sub_0032F7B8 via the temp buffer) are untouched and behave as
    // before.
    //
    // Incoming arguments (same as the guest functions receive):
    //   a0 = EE destination, a1 = byte offset inside FILEn.BIN,
    //   a2 = byte size, a3 = file index (0..3 -> FILE1..FILE4).
    // The guest helpers sectorize a1/a2 exactly like this before the RPC:
    //   sectors = ((int32_t)x < 0 ? x + 0x7FF : x) >> 11
    // ---------------------------------------------------------------------------
    constexpr uint32_t kCdSectorSize = 2048u;
    constexpr uint32_t kSoundmanFileBaseTable = 0x000486C4u; // SOUNDMAN.IRX: FILEn.BIN base LSN, indexed by w3

    uint32_t toSectors(uint32_t value)
    {
        const int32_t signedValue = static_cast<int32_t>(value);
        return static_cast<uint32_t>(signedValue < 0 ? signedValue + 0x7FF : signedValue) >> 11;
    }

    bool loadFileRangeToEe(PS2Runtime &runtime,
                           uint8_t *rdram,
                           uint32_t dest,
                           uint32_t posSectors,
                           uint32_t sizeSectors,
                           uint32_t fileIndex)
    {
        if (sizeSectors == 0u)
        {
            return true;
        }
        const uint64_t byteCount64 = static_cast<uint64_t>(sizeSectors) * kCdSectorSize;
        const uint64_t fileOffset = static_cast<uint64_t>(posSectors) * kCdSectorSize;

        if (fileIndex > 3u)
        {
            std::cerr << "[ufe3] stream load: bad file index " << fileIndex << std::endl;
            return false;
        }

        const std::string fileName = "FILE" + std::to_string(fileIndex + 1u) + ".BIN";
        const std::filesystem::path filePath = PS2Runtime::getIoPaths().cdRoot / fileName;

        std::ifstream file(filePath, std::ios::binary);
        if (!file.is_open())
        {
            std::cerr << "[ufe3] stream load: cannot open " << filePath.string() << std::endl;
            return false;
        }
        file.seekg(static_cast<std::streamoff>(fileOffset), std::ios::beg);
        if (!file.good())
        {
            std::cerr << "[ufe3] stream load: seek failed in " << filePath.string()
                      << " at 0x" << std::hex << fileOffset << std::dec << std::endl;
            return false;
        }

        std::vector<uint8_t> data(static_cast<size_t>(byteCount64));
        file.read(reinterpret_cast<char *>(data.data()), static_cast<std::streamsize>(data.size()));
        if (!file.good())
        {
            std::cerr << "[ufe3] stream load: short read from " << filePath.string()
                      << " at 0x" << std::hex << fileOffset << " len=0x" << data.size() << std::dec << std::endl;
            return false;
        }

        // cmd 0x1B jobs (SOUNDMAN's own "copy into the buffer allocated by cmd 1")
        // usually target IOP RAM (e.g. 0x1782C0), cmd 0x1A jobs target EE RAM
        // (e.g. 0xBFCCC0); a few cmd 0x1B jobs carry EE destinations as well.
        // Deliver each range to the address space the address belongs to.
        const uint32_t physical = dest & 0x1FFFFFFFu;
        if (physical < 0x00200000u)
        {
            if (!runtime.writeIopMemory(physical, data.data(), data.size()))
            {
                std::cerr << "[ufe3] stream load: IOP write failed at 0x" << std::hex << dest << std::dec << std::endl;
                return false;
            }
            return true;
        }

        const uint32_t destOffset = dest & PS2_RAM_MASK;
        const uint64_t maxBytes = static_cast<uint64_t>(PS2_RAM_SIZE - destOffset);
        if (data.size() > maxBytes)
        {
            std::cerr << "[ufe3] stream load clipped: dest=0x" << std::hex << dest
                      << " size=0x" << data.size() << std::dec << std::endl;
            data.resize(static_cast<size_t>(maxBytes));
        }
        std::memcpy(rdram + destOffset, data.data(), data.size());
        return true;
    }

    void ufe3SoundmanLoad(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime)
    {
        const uint32_t dest = getRegU32(ctx, 4);  // a0
        const uint32_t pos = getRegU32(ctx, 5);   // a1: byte offset inside FILEn.BIN
        const uint32_t size = getRegU32(ctx, 6);  // a2: byte size
        const uint32_t fileIndex = getRegU32(ctx, 7); // a3: w3 (0..3)

        const uint32_t posSectors = toSectors(pos);
        const uint32_t sizeSectors = toSectors(size);

        const bool ok = loadFileRangeToEe(*runtime, rdram, dest, posSectors, sizeSectors, fileIndex);
        // The real SOUNDMAN returns its job slot id (1) on success, -1 on failure;
        // sub_0032F050 stores it into the queue entry and polls sub_00356A18 with it.
        setReturnS32(ctx, ok ? 1 : -1);
    }

    void ufe3SoundmanLoadDone(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime)
    {
        // cmd 0x1D ("is job done?"): the load above completed synchronously.
        // The real query returns nonzero when done; sub_00356A18 then reports 1.
        (void)rdram;
        (void)runtime;
        setReturnS32(ctx, 1);
    }

    // ---------------------------------------------------------------------------
    // ERX module loading (liberx / modload replacement) -- see erx/step3/README.md.
    //
    // The boot load loop (0x276408..0x276504, descriptors at 0x3D3468) calls two
    // modload import stubs per module (erx/README.md section 6a):
    //   0x3723E0 (modload #8  "load")  (a0=path, a1=flags|0x100, a2=0) -> handle >= 0
    //   0x372420 (modload #16 "start") (a0=handle, a1=path, a2=0, a3=outStruct) -> >= 0
    // On real hardware liberx/ELOADP loads and relocates the ERX files. Here the 59
    // modules are pre-linked (erx/erx_prelink.py) and AOT-recompiled (erx/step2), so:
    //   "load"  = copy erx/out/<MOD>.bin (image incl. relocated .data/.erx.lib) to its
    //             fixed base; idempotent, returns index+1 as the handle.
    //   "start" = PS2Runtime::bindErxImport for every main-side stub slot of this
    //             module's exported library (the shared "Misn" slots re-bind to the
    //             mission module being started), then call the module's start
    //             function (export word 0) the way sceErxStartModule does.
    // ---------------------------------------------------------------------------
    constexpr uint32_t kErxRegionBase = 0x01C00000u; // module images live here (erx/out/manifest.json)

    void setGprU32(R5900Context *ctx, int reg, uint32_t value)
    {
        if (reg <= 0 || reg > 31)
        {
            return;
        }
        // Same convention as setReturnU32: 32-bit values are sign-extended into the GPR.
        ctx->r[reg] = _mm_set_epi64x(0, static_cast<int64_t>(static_cast<int32_t>(value)));
    }

    uint32_t readGuestU32(const uint8_t *rdram, uint32_t addr)
    {
        const uint32_t phys = addr & PS2_RAM_MASK;
        if (static_cast<uint64_t>(phys) + 4u > PS2_RAM_SIZE)
        {
            return 0u;
        }
        uint32_t value = 0u;
        std::memcpy(&value, rdram + phys, sizeof(value));
        return value;
    }

    void writeGuestU32(uint8_t *rdram, uint32_t addr, uint32_t value)
    {
        const uint32_t phys = addr & PS2_RAM_MASK;
        if (static_cast<uint64_t>(phys) + 4u > PS2_RAM_SIZE)
        {
            return;
        }
        std::memcpy(rdram + phys, &value, sizeof(value));
    }

    std::string readGuestCString(const uint8_t *rdram, uint32_t addr)
    {
        const uint32_t phys = addr & PS2_RAM_MASK;
        std::string out;
        for (uint32_t i = 0; i < 512u && phys + i < PS2_RAM_SIZE; ++i)
        {
            const char c = static_cast<char>(rdram[phys + i]);
            if (c == '\0')
            {
                break;
            }
            out.push_back(c);
        }
        return out;
    }

    // "cdrom0:\ERX\PLAYER00\PL_00.ERX;1" -> "PL_00" (uppercased).
    std::string erxModuleNameFromPath(const std::string &path)
    {
        const size_t slash = path.find_last_of("\\/");
        std::string name = (slash == std::string::npos) ? path : path.substr(slash + 1);
        const size_t end = name.find_first_of(".;");
        if (end != std::string::npos)
        {
            name = name.substr(0, end);
        }
        for (char &c : name)
        {
            c = static_cast<char>(std::toupper(static_cast<unsigned char>(c)));
        }
        return name;
    }

    int erxModuleIndexByName(const std::string &name)
    {
        for (uint32_t i = 0; i < kErxModuleCount; ++i)
        {
            if (name == kErxModules[i].name)
            {
                return static_cast<int>(i);
            }
        }
        return -1;
    }

    // The runner runs from disc/; find the project root's erx/out directory by
    // walking up from the working directory (PS2X_ERX_DIR overrides).
    const std::filesystem::path &erxOutDir()
    {
        static const std::filesystem::path dir = []()
        {
            if (const char *env = std::getenv("PS2X_ERX_DIR"); env && *env)
            {
                return std::filesystem::path(env);
            }
            std::filesystem::path p = std::filesystem::current_path();
            for (int depth = 0; depth < 6; ++depth, p = p.parent_path())
            {
                const std::filesystem::path cand = p / "erx" / "out";
                std::error_code ec;
                if (std::filesystem::exists(cand / "manifest.json", ec))
                {
                    return cand;
                }
                if (p == p.root_path() || p.empty())
                {
                    break;
                }
            }
            return std::filesystem::path("erx/out");
        }();
        return dir;
    }

    std::vector<uint8_t> &erxLoadedFlags()
    {
        static std::vector<uint8_t> flags(kErxModuleCount, 0);
        return flags;
    }

    void erxTrace(bool enabled, const char *fmt, ...) __attribute__((format(printf, 2, 3)));

    void erxTrace(bool enabled, const char *fmt, ...)
    {
        if (!enabled)
        {
            return;
        }
        std::fprintf(stderr, "[erx] ");
        va_list args;
        va_start(args, fmt);
        std::vfprintf(stderr, fmt, args);
        va_end(args);
        std::fprintf(stderr, "\n");
    }

    // Call the module's start function (export word 0 = first quadruple word of its
    // .erx.lib entry) the way sceErxStartModule does at 0x36f330..0x36f358 in
    // work/re/main.s:
    //   fn  = word[entry+0x20] (export word 0; the quadruple words 0..3 are identical
    //         in all 59 modules and point at a `jr $ra` liberx-entry stub),
    //   gp  = word[entry+0x24] (export word 1, loaded into $gp around the call),
    //   v0  preset to fn (the `jalr $2` sequence leaves v0 = fn; the stub's `jr $ra`
    //         then returns it, and sceErxStartModule checks ret&3 == 0 = success),
    //   a0=0, a1=argc, a2=argv, a3=entry. argv is a {path, NULL} vector we build in a
    //   small guest block; the exact argv sceErxStartModule builds comes from the
    //   ELOADP internals (unknowable without running liberx) and is unobservable
    //   because every start function is a bare `jr $ra` stub (verified over all 59
    //   images).
    // Returns the start function's v0. ctx->pc is left where the callee put it so
    // the dispatcher resumes exactly as after a guest `jal`.
    uint32_t erxCallModuleStart(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime,
                                const ErxModuleInfo &module, uint32_t pathPtr, bool trace)
    {
        const uint32_t entry = module.erxLibEntry;
        const uint32_t fn = readGuestU32(rdram, entry + 0x20u);
        const uint32_t gp = readGuestU32(rdram, entry + 0x24u);
        if (fn == 0u || fn == 0xFFFFFFFFu)
        {
            erxTrace(trace, "start %s: no start function (export word 0 = 0x%08x)", module.name, fn);
            return 2u; // ret&3 == 2: sceErxStartModule's "done" path
        }

        // argv = { path, NULL } in a persistent guest block (one per process).
        static uint32_t argvBlock = 0u;
        if (argvBlock == 0u)
        {
            argvBlock = runtime->guestMalloc(8u);
        }
        writeGuestU32(rdram, argvBlock + 0u, pathPtr);
        writeGuestU32(rdram, argvBlock + 4u, 0u);

        const uint32_t savedGp = getRegU32(ctx, 28);
        const uint32_t selfPc = ctx->pc; // our own stub-slot address
        setGprU32(ctx, 4, 0u);           // a0 = 0
        setGprU32(ctx, 5, 1u);           // a1 = argc
        setGprU32(ctx, 6, argvBlock);    // a2 = argv
        setGprU32(ctx, 7, entry);        // a3 = .erx.lib entry
        setGprU32(ctx, 2, fn);           // v0 = fn, exactly like `lw $2,0x1c($19); jalr $2`
        setGprU32(ctx, 28, gp);          // gp = export word 1

        ctx->pc = fn;
        PS2Runtime::RecompiledFunction startFn = runtime->lookupFunction(fn);
        startFn(rdram, ctx, runtime);
        const uint32_t ret = getRegU32(ctx, 2);

        if (ctx->pc == fn)
        {
            // Callee was a C++-style handler that never moved the PC: behave like a
            // normal return so the dispatcher falls through to the caller's $ra.
            ctx->pc = selfPc;
        }
        setGprU32(ctx, 28, savedGp);

        return ret;
    }

    // modload #8 "load": install the pre-linked image for the requested module.
    void ufe3ErxLoadImpl(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime)
    {
        static const bool trace = std::getenv("PS2X_TRACE_ERX") != nullptr;
        const uint32_t pathPtr = getRegU32(ctx, 4);
        const std::string path = readGuestCString(rdram, pathPtr);
        const std::string name = erxModuleNameFromPath(path);
        const int index = erxModuleIndexByName(name);
        if (index < 0)
        {
            // Not one of the 59 ERX modules. Never fail: the callers retry forever
            // on negative returns (unbounded `bltzl` retry in the load loop). Log
            // once per distinct path and hand out a dummy handle.
            static std::vector<std::string> reported;
            if (std::find(reported.begin(), reported.end(), path) == reported.end())
            {
                reported.push_back(path);
                std::cerr << "[erx] load: no ERX module for path '" << path
                          << "' (non-ERX modload), returning dummy handle" << std::endl;
            }
            setReturnS32(ctx, 0x100);
            return;
        }
        const ErxModuleInfo &module = kErxModules[index];
        const uint32_t handle = static_cast<uint32_t>(index) + 1u;

        std::vector<uint8_t> &loaded = erxLoadedFlags();
        if (!loaded[index])
        {
            const std::filesystem::path binPath = erxOutDir() / (std::string(module.name) + ".bin");
            std::ifstream file(binPath, std::ios::binary | std::ios::ate);
            if (!file.is_open())
            {
                std::cerr << "[erx] load " << module.name << ": cannot open " << binPath.string() << std::endl;
                setReturnS32(ctx, -1);
                return;
            }
            const std::streamsize fileSize = file.tellg();
            if (fileSize != static_cast<std::streamsize>(module.size))
            {
                std::cerr << "[erx] load " << module.name << ": size mismatch (" << fileSize
                          << " != " << module.size << ") for " << binPath.string() << std::endl;
                setReturnS32(ctx, -1);
                return;
            }
            std::vector<uint8_t> image(static_cast<size_t>(fileSize));
            file.seekg(0, std::ios::beg);
            file.read(reinterpret_cast<char *>(image.data()), fileSize);
            const uint32_t phys = module.base & PS2_RAM_MASK;
            if (static_cast<uint64_t>(phys) + image.size() > PS2_RAM_SIZE)
            {
                std::cerr << "[erx] load " << module.name << ": image exceeds RAM" << std::endl;
                setReturnS32(ctx, -1);
                return;
            }
            std::memcpy(rdram + phys, image.data(), image.size());
            loaded[index] = 1;
            erxTrace(trace, "load %s base=%08x size=%08x handle=%u tick=%llu path=%s",
                     module.name, module.base, module.size, handle,
                     static_cast<unsigned long long>(runtime->eeScheduler().currentVSyncTick()),
                     path.c_str());
        }
        else
        {
            erxTrace(trace, "load %s base=%08x size=%08x handle=%u tick=%llu (already loaded, idempotent)",
                     module.name, module.base, module.size, handle,
                     static_cast<unsigned long long>(runtime->eeScheduler().currentVSyncTick()));
        }
        setReturnS32(ctx, static_cast<int32_t>(handle));
    }

    // modload #16 "start": bind the module's main-side import stub slots and call
    // its start function.
    void ufe3ErxStartImpl(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime)
    {
        static const bool trace = std::getenv("PS2X_TRACE_ERX") != nullptr;
        const uint32_t handle = getRegU32(ctx, 4);
        const uint32_t pathPtr = getRegU32(ctx, 5);
        const uint32_t outStruct = getRegU32(ctx, 7);
        const std::string path = readGuestCString(rdram, pathPtr);

        int index = -1;
        if (handle >= 1u && handle <= kErxModuleCount)
        {
            index = static_cast<int>(handle - 1u);
        }
        if (index < 0)
        {
            index = erxModuleIndexByName(erxModuleNameFromPath(path));
        }
        if (index < 0)
        {
            // Non-ERX modload "start" (dummy handle from the load hook, or an
            // unrelated caller). Nothing to bind or call: report success, log once
            // per handle so a retrying caller cannot spam the log.
            static std::vector<uint32_t> reported;
            if (std::find(reported.begin(), reported.end(), handle) == reported.end())
            {
                reported.push_back(handle);
                std::cerr << "[erx] start: no ERX module for handle=" << handle << " path='" << path
                          << "' (non-ERX modload), no-op" << std::endl;
            }
            if (outStruct != 0u)
            {
                writeGuestU32(rdram, outStruct, 0u);
            }
            setReturnS32(ctx, 0);
            return;
        }
        const ErxModuleInfo &module = kErxModules[index];

        // Make sure the image is installed even if "start" is ever reached without a
        // preceding "load" for the same module.
        if (!erxLoadedFlags()[index])
        {
            setGprU32(ctx, 4, pathPtr);
            ufe3ErxLoadImpl(rdram, ctx, runtime);
            if (getRegU32(ctx, 2) & 0x80000000u)
            {
                setReturnS32(ctx, -1);
                return;
            }
        }

        // Bind every main-side stub slot of this module's exported library. The
        // shared "Misn" slots (0x35BA18..0x35BA38) are included in each MISN module's
        // binding list, so starting a mission module re-binds them to it -- exactly
        // the sceErxStartModule behaviour (erx/step2/README.md section 5.1.2).
        for (uint32_t i = 0; i < module.bindingCount; ++i)
        {
            PS2Runtime::bindErxImport(module.bindings[i].slot, module.bindings[i].target);
        }

        const uint32_t startRet = erxCallModuleStart(rdram, ctx, runtime, module, pathPtr, trace);

        if (outStruct != 0u)
        {
            // sceErxStartModule stores the start return code at outStruct+0 (0x36f388).
            writeGuestU32(rdram, outStruct, startRet);
        }

        erxTrace(trace, "start %s base=%08x handle=%u tick=%llu bindings=%u%s start=%08x ret=%08x",
                 module.name, module.base, handle,
                 static_cast<unsigned long long>(runtime->eeScheduler().currentVSyncTick()),
                 module.bindingCount,
                 (std::string(module.name).rfind("MISN", 0) == 0) ? " (Misn slots rebound)" : "",
                 readGuestU32(rdram, module.erxLibEntry + 0x20u), startRet);

        setReturnS32(ctx, 0);
    }

    // Return-to-caller rule shared by all loader handlers: a replacement handler is
    // normally reached through dispatchGuestBranch (which falls through when the
    // handler leaves ctx->pc alone), but it can also be dispatched at the top level
    // (e.g. after another stub's trap fall-through). In the latter case leaving
    // ctx->pc on the handler address would re-dispatch it forever, so return like
    // callErxImport's tail-call trampoline does: fall back to the guest $ra.
    void ufe3ErxReturnToCaller(R5900Context *ctx, uint32_t selfPc)
    {
        if (ctx->pc == selfPc)
        {
            ctx->pc = getRegU32(ctx, 31);
        }
    }

    void ufe3ErxLoad(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime)
    {
        const uint32_t selfPc = ctx->pc;
        ufe3ErxLoadImpl(rdram, ctx, runtime);
        ufe3ErxReturnToCaller(ctx, selfPc);
    }

    void ufe3ErxStart(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime)
    {
        const uint32_t selfPc = ctx->pc;
        ufe3ErxStartImpl(rdram, ctx, runtime);
        ufe3ErxReturnToCaller(ctx, selfPc);
    }

    // ---------------------------------------------------------------------------
    // Kernel import stubs (sysmem/loadcore/modload, 0x372200..0x372480). These are
    // `break 0,1` slots just like the character stubs but they are NOT ERX
    // bindings (erx/step2/README.md section 5.1.3); before this step they were
    // reached through the generated trap fall-through, which returned to the caller
    // with an undefined v0. With per-slot dispatch they would instead take the
    // unlinked trap and park the thread, so the override gives every kernel slot a
    // deterministic handler:
    //   * 0x372400 (modload #0xC, LoadModule) returns -1: its caller is liberx's
    //     ELOADP attach (0x36AE78..0x36AF28) which has a documented graceful
    //     failure path ("liberx: ELOADP is not available", stores -1, continues).
    //     The ERX modules do not need ELOADP: their load/start is hooked above.
    //   * all other kernel slots return 0 (success) -- the only boot-time callers
    //     are the game's library-registration loop (0x2762D0.., return ignored)
    //     and liberx init's ignored sysmem call (0x36AF18).
    //
    // Each slot is hooked through BOTH mechanisms, because the code generator uses
    // two dispatch paths (verified in work/output/sub_00276298_0x276298.cpp):
    //   * `jal <slot>` goes through dispatchGuestBranch -> the function table
    //     (reached by replaceFunction),
    //   * `j <slot>` (tail jump) emits a DIRECT C++ call to the generated slot
    //     body, which bypasses replaceFunction and runs callErxImport instead
    //     (reached by bindErxImport; callErxImport's tail-call trampoline returns
    //     to the guest $ra exactly like the function-table path).
    // The bindErxImport targets are synthetic guest addresses registered in the
    // overflow registry (nothing ever executes guest code at them).
    // ---------------------------------------------------------------------------
    constexpr uint32_t kErxStubTargetOk = 0x01F80000u;
    constexpr uint32_t kErxStubTargetFail = 0x01F80004u;
    constexpr uint32_t kErxStubTargetLoad = 0x01F80008u;
    constexpr uint32_t kErxStubTargetStart = 0x01F8000Cu;

    void ufe3KernelStubLoadModuleUnavailable(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime)
    {
        (void)rdram;
        (void)runtime;
        const uint32_t selfPc = ctx->pc;
        setReturnS32(ctx, -1);
        ufe3ErxReturnToCaller(ctx, selfPc);
    }

    void ufe3KernelStubOk(uint8_t *rdram, R5900Context *ctx, PS2Runtime *runtime)
    {
        (void)rdram;
        (void)runtime;
        const uint32_t selfPc = ctx->pc;
        setReturnS32(ctx, 0);
        ufe3ErxReturnToCaller(ctx, selfPc);
    }

    // Every `break 0,1; addiu $zero,$zero,N` slot in the kernel stub-code ranges
    // (sysmem 0x372200..0x372268, loadcore 0x372278..0x3723B8, modload
    // 0x3723C8..0x372480), scanned from disc/SLPS_254.41. 0x3723E0/0x372420 get the
    // ERX hooks, 0x372400 the ELOADP failure handler; the rest return 0.
    constexpr uint32_t kKernelStubSlots[] = {
        0x00372200u, 0x00372208u, 0x00372210u, 0x00372218u, 0x00372220u, 0x00372228u,
        0x00372230u, 0x00372238u, 0x00372240u, 0x00372248u, 0x00372250u, 0x00372258u,
        0x00372278u, 0x00372280u, 0x00372288u, 0x00372290u, 0x00372298u, 0x003722A0u,
        0x003722A8u, 0x003722B0u, 0x003722B8u, 0x003722C0u, 0x003722C8u, 0x003722D0u,
        0x003722D8u, 0x003722E0u, 0x003722E8u, 0x003722F0u, 0x003722F8u, 0x00372300u,
        0x00372308u, 0x00372310u, 0x00372318u, 0x00372320u, 0x00372328u, 0x00372330u,
        0x00372338u, 0x00372340u, 0x00372348u, 0x00372350u, 0x00372358u, 0x00372360u,
        0x00372368u, 0x00372370u, 0x00372378u, 0x00372380u, 0x00372388u, 0x00372390u,
        0x00372398u, 0x003723A0u, 0x003723A8u,
        0x003723C8u, 0x003723D0u, 0x003723D8u, 0x003723E0u, 0x003723E8u, 0x003723F0u,
        0x003723F8u, 0x00372400u, 0x00372408u, 0x00372410u, 0x00372418u, 0x00372420u,
        0x00372428u, 0x00372430u, 0x00372438u, 0x00372440u, 0x00372448u, 0x00372450u,
        0x00372458u, 0x00372460u, 0x00372468u, 0x00372470u,
    };

    // PS2X_ERX_SELFTEST=1 support: invoke the two modload hooks through
    // PS2Runtime::callErxImport -- the exact dispatch path the generated slot
    // bodies use for a direct `j` to the stub -- for every module. Verifies
    // path->module mapping, image install, handle allocation, binding creation,
    // the module start-function call, and load idempotence.
    void ufe3ErxSelfTest(PS2Runtime &runtime)
    {
        uint8_t *rdram = runtime.memory().getRDRAM();
        if (!rdram)
        {
            std::cerr << "[erx] selftest: no RDRAM" << std::endl;
            return;
        }
        const uint32_t pathBuf = runtime.guestMalloc(256u);
        R5900Context ctx{};
        uint32_t ok = 0;
        for (uint32_t i = 0; i < kErxModuleCount; ++i)
        {
            const ErxModuleInfo &module = kErxModules[i];
            const std::string path = module.discPath;
            std::memcpy(rdram + (pathBuf & PS2_RAM_MASK), path.c_str(), path.size() + 1);

            setGprU32(&ctx, 4, pathBuf); // a0 = path
            runtime.callErxImport(rdram, &ctx, 0x003723E0u);
            const uint32_t handle = getRegU32(&ctx, 2);

            setGprU32(&ctx, 4, pathBuf); // a0 = path again (idempotence)
            runtime.callErxImport(rdram, &ctx, 0x003723E0u);
            const uint32_t handleAgain = getRegU32(&ctx, 2);

            setGprU32(&ctx, 4, handle);  // a0 = handle
            setGprU32(&ctx, 5, pathBuf); // a1 = path
            setGprU32(&ctx, 7, 0u);      // a3 = no out struct
            runtime.callErxImport(rdram, &ctx, 0x00372420u);
            const uint32_t startRet = getRegU32(&ctx, 2);

            const bool good = handle == i + 1u && handleAgain == handle && startRet == 0u;
            ok += good ? 1u : 0u;
            if (!good)
            {
                std::cerr << "[erx] selftest FAIL " << module.name << ": handle=" << handle
                          << " again=" << handleAgain << " start=" << startRet << std::endl;
            }
        }
        std::cerr << "[erx] selftest: " << ok << "/" << kErxModuleCount
                  << " modules load+start+idempotence OK" << std::endl;
    }

    void applyUfe3(PS2Runtime &runtime)
    {
        // ERX module images are pre-linked into 0x01C00000..0x01DECA6C (see
        // erx/out/manifest.json). The runtime's HLE guest heap would otherwise run
        // to its 0x01F00000 hard limit and could hand out memory on top of them, so
        // cap the heap at the module region's base. This runs during ELF load, before
        // any guest allocation exists, and UFE3 never re-configures the heap at
        // runtime (it executes no SetupHeap/EndOfHeap syscalls -- verified against
        // the ELF), so the existing configureGuestHeap API is sufficient.
        runtime.configureGuestHeap(0u, kErxRegionBase);

        // Register the AOT-recompiled ERX module functions (all 59 modules) in the
        // overflow registry before anything can jump to 0x01C00000+.
        erxRegisterModuleFunctions();

        // newlib _memalign_r carves the aligned block out of a _malloc_r chunk and _free_r's the
        // leading slack; with the HLE heap that frees the whole block. memalign@0x3A0198 is bound in
        // ufe3.toml, but other wrappers tail-jump straight to _memalign_r, which has no function start.
        if (!ps2_game_overrides::bindAddressHandler(runtime, 0x003A01C0u, "memalign_r"))
        {
            std::cerr << "[ufe3] failed to bind _memalign_r@0x3A01C0" << std::endl;
        }

        // See the SOUNDMAN load bypass above.
        if (!runtime.replaceFunction(0x00356948u, &ufe3SoundmanLoad) ||
            !runtime.replaceFunction(0x00356998u, &ufe3SoundmanLoad) ||
            !runtime.replaceFunction(0x00356A18u, &ufe3SoundmanLoadDone))
        {
            std::cerr << "[ufe3] failed to bind SOUNDMAN load overrides" << std::endl;
        }

        // See the ERX loader above (erx/step3/README.md). The step-2 recompiler made
        // every 8-byte import stub slot its own dispatchable entry, so the hooks bind
        // each precisely: 0x3723E0/0x372420 are the modload load/start hooks the boot
        // load loop at 0x276408 calls per module, the other kernel stubs get
        // deterministic no-op returns (see the kernel stub section above).
        bool erxHooksOk = true;
        erxHooksOk = runtime.replaceFunction(kErxStubTargetOk, &ufe3KernelStubOk) && erxHooksOk;
        erxHooksOk = runtime.replaceFunction(kErxStubTargetFail, &ufe3KernelStubLoadModuleUnavailable) && erxHooksOk;
        erxHooksOk = runtime.replaceFunction(kErxStubTargetLoad, &ufe3ErxLoad) && erxHooksOk;
        erxHooksOk = runtime.replaceFunction(kErxStubTargetStart, &ufe3ErxStart) && erxHooksOk;
        for (uint32_t slot : kKernelStubSlots)
        {
            PS2Runtime::RecompiledFunction handler = &ufe3KernelStubOk;
            uint32_t target = kErxStubTargetOk;
            if (slot == 0x003723E0u)
            {
                handler = &ufe3ErxLoad;
                target = kErxStubTargetLoad;
            }
            else if (slot == 0x00372420u)
            {
                handler = &ufe3ErxStart;
                target = kErxStubTargetStart;
            }
            else if (slot == 0x00372400u)
            {
                handler = &ufe3KernelStubLoadModuleUnavailable;
                target = kErxStubTargetFail;
            }
            erxHooksOk = runtime.replaceFunction(slot, handler) && erxHooksOk;
            PS2Runtime::bindErxImport(slot, target);
        }
        if (!erxHooksOk)
        {
            std::cerr << "[ufe3] failed to bind some ERX/kernel stub overrides" << std::endl;
        }

        // PS2X_ERX_SELFTEST=1: drive every module's load/start through the real
        // callErxImport dispatch path (the same one the generated slot bodies use),
        // exactly once at startup. This both verifies the hooks end-to-end without
        // waiting for the game's on-demand loader and pre-installs all images; the
        // real loader calls stay idempotent ("already loaded").
        if (std::getenv("PS2X_ERX_SELFTEST") != nullptr)
        {
            ufe3ErxSelfTest(runtime);
        }
    }
}

PS2_REGISTER_GAME_OVERRIDE("Ultraman Fighting Evolution 3", "SLPS_254.41", 0x0020001Cu, 0x80E63037u, applyUfe3);
