#!/usr/bin/env python3
"""Generate the ERX module metadata table (C++) used by game/ufe3_overrides.cpp.

Inputs (both produced by earlier steps, see erx/README.md and erx/step2/README.md):
  erx/out/manifest.json            step 1: pre-linked module images + layout
                                   (name, disc path, base, size, section_layout, exports)
  erx/step2/out/erx_bindings.json  step 2: main-ELF .erx.stub slot -> module export
                                   bindings ({library, slot, index, module, target})

Output:
  erx/step3/out/erx_tables.h       struct declarations + externs
  erx/step3/out/erx_tables.cpp     the generated tables

Why a build-time C++ table instead of parsing the JSON at runtime: the runner runs
from disc/ and the override would otherwise need a JSON parser and path discovery
for metadata; the only thing still read at runtime is the raw module image
(erx/out/<MOD>.bin), which must stay a data file. The table is regenerated by
rebuild.sh whenever the inputs change.

Usage: python3 erx/step3/erx_tables.py [--root <repo>]
"""
import argparse
import json
import os

HEADER = '''// Generated by erx/step3/erx_tables.py -- do not edit.
#pragma once
#include <cstdint>

struct ErxModuleBinding
{
    uint32_t slot;   // main-ELF .erx.stub slot address (break 0,1 pair)
    uint32_t target; // module export guest address the slot binds to
};

struct ErxModuleInfo
{
    const char *name;      // "PL_00", "MISN_7", ...
    const char *discPath;  // path as the game's load loop passes it (informational)
    uint32_t base;         // fixed guest base of the pre-linked image
    uint32_t size;         // image size in bytes
    uint32_t erxLibEntry;  // guest address of the module's "eRxLiB" export entry
    const ErxModuleBinding *bindings;
    uint32_t bindingCount;
};

extern const ErxModuleInfo kErxModules[];
extern const uint32_t kErxModuleCount;
'''


def module_disc_path(manifest_path):
    """'disc/ERX/PLAYER00/PL_00.ERX' -> 'cdrom0:\\\\ERX\\\\PLAYER00\\\\PL_00.ERX;1'"""
    rel = manifest_path.replace('disc/', '').replace('disc\\\\', '')
    return 'cdrom0:\\' + rel.replace('/', '\\') + ';1'


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--root', default=os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
    ap.add_argument('--out', default=None, help='output dir (default <root>/erx/step3/out)')
    args = ap.parse_args()
    root = os.path.abspath(args.root)
    out_dir = args.out or os.path.join(root, 'erx', 'step3', 'out')
    os.makedirs(out_dir, exist_ok=True)

    with open(os.path.join(root, 'erx', 'out', 'manifest.json')) as f:
        manifest = json.load(f)
    with open(os.path.join(root, 'erx', 'step2', 'out', 'erx_bindings.json')) as f:
        bindings_doc = json.load(f)

    modules = manifest['modules'] if isinstance(manifest, dict) else manifest
    by_module = {}
    for b in bindings_doc['bindings']:
        by_module.setdefault(b['module'], []).append((b['slot'], b['target']))

    cpp = ['// Generated by erx/step3/erx_tables.py -- do not edit.',
           '#include "erx_tables.h"', '']
    infos = []
    for i, mod in enumerate(modules):
        name = mod['name']
        erxlib = next((s for s in mod['section_layout'] if s['name'] == '.erx.lib'), None)
        if erxlib is None:
            raise SystemExit(f'{name}: no .erx.lib in section_layout')
        entries = sorted(by_module.get(name, []))
        cpp.append(f'static const ErxModuleBinding kErxBindings_{name}[] = {{')
        for slot, target in entries:
            cpp.append(f'    {{ 0x{slot:08X}u, 0x{target:08X}u }},')
        if not entries:
            cpp.append('    { 0u, 0u },')
        cpp.append('};')
        cpp.append('')
        infos.append(
            f'    {{ "{name}", "{module_disc_path(mod["path"]).replace(chr(92), chr(92) * 2)}", 0x{mod["base"]:08X}u, '
            f'0x{mod["size"]:08X}u, 0x{erxlib["addr"]:08X}u, kErxBindings_{name}, '
            f'{len(entries)}u }},')

    cpp.append('const ErxModuleInfo kErxModules[] = {')
    cpp.extend(infos)
    cpp.append('};')
    cpp.append('')
    cpp.append(f'const uint32_t kErxModuleCount = {len(modules)}u;')
    cpp.append('')

    with open(os.path.join(out_dir, 'erx_tables.h'), 'w') as f:
        f.write(HEADER)
    with open(os.path.join(out_dir, 'erx_tables.cpp'), 'w') as f:
        f.write('\n'.join(cpp))

    total = sum(len(by_module.get(m['name'], [])) for m in modules)
    print(f'{len(modules)} modules, {total} bindings -> {out_dir}')


if __name__ == '__main__':
    main()
