#!/usr/bin/env python3
"""Post-process ps2_recomp output for the 59 pre-linked ERX modules.

For each erx/step2/gen/<MOD>/ (produced by ps2_recomp on the wrapper ELFs):
  * keep every generated sub_*.cpp / entry_*.cpp (module recompiled code),
  * drop the per-module register_functions.cpp (its dense table would clash
    with the main game's table symbols),
  * rewrite `#include <ps2_recompiled_functions.h>` / `<ps2_recompiled_stubs.h>`
    to erx_ headers so module code can live next to the main game's generated
    code without include clashes,
  * emit one combined erx_recompiled_functions.h (all module declarations) and
    one erx_register.cpp that registers every module function through
    PS2Runtime::registerOverflowFunction (the overflow registry).

Output goes to erx/step2/out/ (flat). Copy that directory to
ps2xRuntime/src/runner/erx/ to compile the modules into ps2EntryRunner.

Usage: python3 erx/step2/erx_post.py [--root <repo>]
"""
import argparse
import os
import re
import sys

DECL_RE = re.compile(r'^void\s+([A-Za-z_][A-Za-z0-9_]*)\s*\(uint8_t\s*\*\s*rdram,')
ADDR_RE = re.compile(r'_0x([0-9a-fA-F]+)$')


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--root', default=os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
    args = ap.parse_args()
    root = os.path.abspath(args.root)
    step2 = os.path.join(root, 'erx', 'step2')
    gen_dir = os.path.join(step2, 'gen')
    out_dir = os.path.join(step2, 'out')
    os.makedirs(out_dir, exist_ok=True)

    decls = {}  # name -> address
    copied = 0
    modules = sorted(d for d in os.listdir(gen_dir) if os.path.isdir(os.path.join(gen_dir, d)))
    for mod in modules:
        mod_dir = os.path.join(gen_dir, mod)
        header = os.path.join(mod_dir, 'ps2_recompiled_functions.h')
        if not os.path.exists(header):
            raise SystemExit(f'{mod}: missing ps2_recompiled_functions.h')
        with open(header) as f:
            for line in f:
                m = DECL_RE.match(line.strip())
                if not m:
                    continue
                name = m.group(1)
                am = ADDR_RE.search(name)
                if not am:
                    raise SystemExit(f'{mod}: cannot parse address from {name}')
                decls[name] = int(am.group(1), 16)

        for fn in sorted(os.listdir(mod_dir)):
            if not fn.endswith('.cpp') or fn == 'register_functions.cpp':
                continue
            with open(os.path.join(mod_dir, fn)) as f:
                src = f.read()
            src = src.replace('#include <ps2_recompiled_functions.h>', '#include "erx_recompiled_functions.h"')
            src = src.replace('#include <ps2_recompiled_stubs.h>', '#include "erx_recompiled_stubs.h"')
            with open(os.path.join(out_dir, fn), 'w') as f:
                f.write(src)
            copied += 1

    # Combined declarations header.
    with open(os.path.join(out_dir, 'erx_recompiled_functions.h'), 'w') as f:
        f.write('// Generated by erx/step2/erx_post.py -- recompiled ERX module functions.\n')
        f.write('#pragma once\n\n#include <cstdint>\n\nstruct R5900Context;\nclass PS2Runtime;\n\n')
        for name in sorted(decls, key=lambda n: (decls[n], n)):
            f.write(f'void {name}(uint8_t* rdram, R5900Context* ctx, PS2Runtime *runtime);\n')

    with open(os.path.join(out_dir, 'erx_recompiled_stubs.h'), 'w') as f:
        f.write('// Generated by erx/step2/erx_post.py -- no runtime stubs are configured for ERX modules.\n')
        f.write('#pragma once\n')

    # Registration through the overflow function registry.
    #
    # Registration is an explicit function call, NOT a static initializer: the
    # overflow registry map in ps2_runtime.cpp is a namespace-scope object of
    # another translation unit, and a static initializer here can run before that
    # map is constructed (static initialization order fiasco -> SIGFPE inside the
    # map's bucket math). The game override calls erxRegisterModuleFunctions() at
    # runtime-init time (see game/ufe3_overrides.cpp); it is idempotent.
    with open(os.path.join(out_dir, 'erx_register.cpp'), 'w') as f:
        f.write('// Generated by erx/step2/erx_post.py -- registers the recompiled ERX module\n')
        f.write('// functions through PS2Runtime\'s overflow registry (guest PCs outside the\n')
        f.write('// main game\'s dense generated table, e.g. 0x01C00000+).\n')
        f.write('//\n')
        f.write('// Call erxRegisterModuleFunctions() once at runtime-init time; a static\n')
        f.write('// initializer would race the registry map\'s construction (SIOF).\n')
        f.write('#include "ps2_runtime.h"\n#include "erx_recompiled_functions.h"\n\n')
        f.write('void erxRegisterModuleFunctions()\n{\n')
        for name in sorted(decls, key=lambda n: (decls[n], n)):
            f.write(f'    PS2Runtime::registerOverflowFunction(0x{decls[name]:08X}u, {name});\n')
        f.write('}\n')

    print(f'{len(modules)} modules: {copied} function files, {len(decls)} registrations -> {out_dir}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
